### ISSUE TITLE
After filtering, buttons do not work

### ISSUE THREAD

**Issue by Apidra** [MCLACS/CSCI452-FA19-Public#30]
fixed filter to work, before it wasn't. Now after filtering the buttons don't work

**Comment by Apidra** [comment]
well they do work, but they are definitely wonky. needs a look from someone

**Comment by Apidra** [comment]
forgot to mention, my changes are on `bug_fixing` and "fixed" is a little generous in this case...it works! kind of.

**Comment by HermitXVII** [comment]
Filter works now, Except with C++, Could Possibly be an issue with the + character

**Comment by HermitXVII** [comment]
added encodeURIComponent() to our model.filter, now filtering works 100%
