### ISSUE TITLE
server request not sorting properly

### ISSUE THREAD

**Issue by Apidra** [MCLACS/CSCI452-FA19-Public#31]
the server is ignoring our `ORDER BY` clause, resorting to sorting by `SNIP_ID` rather than the category we tell it to sort by.

**Comment by Apidra** [comment]
I hard coded values requestiung `"SELECT * FROM SNIPPET ORDER BY SNIP_LANG DESC"` and it worked. on this end of issues, it's gotta be the way we're making the queries.

**Comment by Apidra** [comment]
it's hacky, but this is working (kind of, a little wonky when switching categories but i haven't looked too far into that part yet) 
`SELECT * FROM SNIPPET " + " ORDER BY " + req.query.category + " " + req.query.order`

**Comment by HermitXVII** [comment]
Everything solved. Works.
