### ISSUE TITLE
Fix SQL Injection Vulnerabilities

### ISSUE THREAD

**Issue by benmichener14** [MCLACS/CSCI452-FA19-Public#47]
As a developer, I want to fix any issues that there are with passing data on the query string so that Bobby Droptables cannot cause any issues with our awesome program.

**Comment by Apidra** [comment]
lol

**Comment by jd6378** [comment]
![image](https://user-images.githubusercontent.com/47004564/66622484-bc2a2f80-ebb5-11e9-97f7-b56fc8394cc6.png)
