### ISSUE TITLE
Get Food and Drinks together

### ISSUE THREAD

**Issue by benmichener14** [MCLACS/CSCI452-FA19-Public#65]
We need to get to know each other in a non-stressful environment. Let's get food a booze. Or not booze, if you don't drink or whatever. But definitely food.

Leave your evening availability below.

**Comment by benmichener14** [comment]
My Availability is as below:
Friday evenings, Tuesdays and Thursdays after 6. 

Mondays and Wednesdays are no go.

**Comment by HermitXVII** [comment]
Monday - Friday after 6 mostly

**Comment by Apidra** [comment]
I'm good pretty much every night except for Wednesday and I've got a radio show Fridays 7-9 (tune in at mcla.edu/wjjw ;) )

**Comment by jd6378** [comment]
I'm free wed-fri after 7
